/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordonnanceur;

import java.awt.BorderLayout;
import java.awt.Label;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Asus
 */
public class Simulateurs extends javax.swing.JFrame {

    /**
     * Creates new form Simulateurs
     */
    static File fich = new File("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/pointeurListeProcessus.txt" );/* Fichier ou j'enregistre "ptr" */
    static File fich2 = new File("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/listeProcessus.txt"); 
    static Processus[] listeProcessus = new Processus[100];  /* Tableau où seront stockés les processus. C'est ce tableau qui va être écrit dans mon fichier "Ordonnancement1.txt" */
    static Politiques f7 = new Politiques(); /* Objet qui permet d'appeler toutes les fonctions dans la classe "Fonction" */
    static int ptr = 0; /* ptr représente l'indice de la prochaine case vide dans mon tableau "listeProcessus". Va etre ecrit dans "Test.txt" */
       
    public Simulateurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        txt_temps_arr = new javax.swing.JTextField();
        txt_duree = new javax.swing.JTextField();
        txt_priorite = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        btn_generer = new javax.swing.JButton();
        label8 = new java.awt.Label();
        btn_ajouter1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label3 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        btn_FIFO = new javax.swing.JButton();
        btn_SJF = new javax.swing.JButton();
        btn_RR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_quant = new javax.swing.JTextField();
        txt_quantum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txt_aleatoire = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_afficher1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 153, 153));
        label2.setText("* Affichage des processus");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, 36));
        getContentPane().add(txt_temps_arr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 42));

        txt_duree.setToolTipText("");
        getContentPane().add(txt_duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 42));
        getContentPane().add(txt_priorite, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 60, 42));

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 60, 40));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Priorité");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 32));

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Nom ");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, 32));

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText("Durée");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, 32));

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Temps d'arrivée");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 32));

        btn_generer.setBackground(new java.awt.Color(0, 153, 153));
        btn_generer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_generer.setText("Afficher");
        btn_generer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genererActionPerformed(evt);
            }
        });
        getContentPane().add(btn_generer, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, -1, -1));

        label8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 153, 153));
        label8.setText("* Ajout d'un processus");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 36));

        btn_ajouter1.setBackground(new java.awt.Color(0, 153, 153));
        btn_ajouter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ajouter1.setText("Ajouter");
        btn_ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajouter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Temps Arrivée", "Durée", "Priorité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 412, 120));

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 102, 102));
        label3.setText("Simulateur d'ordonnencement des processus");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 554, 51));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));
        jPanel1.setLayout(null);

        btn_FIFO.setBackground(new java.awt.Color(255, 51, 51));
        btn_FIFO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_FIFO.setForeground(new java.awt.Color(255, 255, 255));
        btn_FIFO.setText("FIFO");
        btn_FIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FIFOActionPerformed(evt);
            }
        });
        jPanel1.add(btn_FIFO);
        btn_FIFO.setBounds(1070, 70, 83, 53);

        btn_SJF.setBackground(new java.awt.Color(51, 153, 0));
        btn_SJF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_SJF.setForeground(new java.awt.Color(255, 255, 255));
        btn_SJF.setText("SJF");
        btn_SJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SJFActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SJF);
        btn_SJF.setBounds(1070, 160, 83, 52);

        btn_RR.setBackground(new java.awt.Color(0, 0, 255));
        btn_RR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_RR.setForeground(new java.awt.Color(255, 255, 255));
        btn_RR.setText("RR");
        btn_RR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RRActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RR);
        btn_RR.setBounds(1070, 270, 83, 51);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Ordonnanceur");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 20, 174, 27);
        jPanel1.add(txt_quant);
        txt_quant.setBounds(1170, 280, 40, 30);

        txt_quantum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_quantum.setText("Quantium");
        jPanel1.add(txt_quantum);
        txt_quantum.setBounds(1160, 320, 60, 14);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 160, 1030, 80);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 250, 1030, 80);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(140, 30, 2, 2);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(null);
        jScrollPane3.setViewportView(jPanel2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 1030, 80);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1220, 340));

        txt_aleatoire.setToolTipText("");
        getContentPane().add(txt_aleatoire, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("*Génerer alétaoirement :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, 30));

        btn_afficher1.setBackground(new java.awt.Color(0, 153, 153));
        btn_afficher1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_afficher1.setText("Génerer");
        btn_afficher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_afficher1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_afficher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void btn_genererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genererActionPerformed
        // TODO add your handling code here:
        if ( fich2.length() == 0 ){

            JOptionPane.showMessageDialog(null," Aucun processus trouvé !! ");

        }
        else
        {  String [] colname ={ "Nom", "Temps Arrivée", "Durée", "Priorité"};

            Object[][] object = new Object[100][100];
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
            
            for (int i=0;i<ptr;i++)
            {

                model.addRow(new Object []{listeProcessus[i].getNomProcessus(),listeProcessus[i].getTempArriveeProcessus(),listeProcessus[i].getDureeProcessus(),listeProcessus[i].getPrioriteProcessus()});

            }
        }

    }//GEN-LAST:event_btn_genererActionPerformed

    private void btn_ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter1ActionPerformed
        // TODO add your handling code here:

        if ("".equals(txt_duree.getText()) && "".equals(txt_nom.getText()) && "".equals(txt_temps_arr.getText()))
        {
            JOptionPane.showMessageDialog(null," Vous devez remplir tous les champs  !! "); }
        else
        {     String nom_pr=txt_nom.getText();
            int duree=Integer.parseInt(txt_duree.getText());
            int temps_arr=Integer.parseInt(txt_temps_arr.getText());
            int priorite=Integer.parseInt(txt_priorite.getText());

            listeProcessus = f7.registerProcessus(ptr, listeProcessus ,nom_pr ,duree,priorite,temps_arr);
            ptr++;

            /* ########## SAUVEGARDE DE PTR ########## */

            try {
                ObjectOutputStream out1 = new ObjectOutputStream(new FileOutputStream("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/pointeurListeProcessus.txt"));
                out1.writeInt(ptr);
                out1.close();
            }
            catch (Exception e){
                e.printStackTrace();
            }

            /* ########## FIN SAUVEGARDE DE PTR ########## */
            /* ########## SAUVEGARDE DE LISTEPROCESSUS ########## */

            try {
                ObjectOutputStream out2 = new ObjectOutputStream(new FileOutputStream("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/listeProcessus.txt"));
                out2.writeObject(listeProcessus);
                out2.flush();
                out2.close();
            }
            catch (Exception e){
                e.printStackTrace();
            }

            /* ########## FIN SAUVEGARDE DE LISTEPROCESSUS ########## */

            txt_nom.setText("");
            txt_duree.setText("");
            txt_priorite.setText("");
            txt_temps_arr.setText("");

        }

    }//GEN-LAST:event_btn_ajouter1ActionPerformed

    private void btn_FIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FIFOActionPerformed
        // TODO add your handling code here:
       
       // TODO add your handling code here:
        jPanel2.removeAll();
        
       float[] res=new float [2];
        Border border = LineBorder.createGrayLineBorder();
        res=f7. FIFO( ptr, listeProcessus);
        int y = 10;
        javax.swing.JLabel[] tempNomSousAgent = new javax.swing.JLabel[ ptr];
       
           
         for(int i=0;i<ptr;i++){ 

        tempNomSousAgent[i] = new javax.swing.JLabel();
        tempNomSousAgent[i].setText(listeProcessus[i].getNomProcessus());
        tempNomSousAgent[i].setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tempNomSousAgent[i].setForeground(new java.awt.Color(0, 153, 153));
        tempNomSousAgent[i].setBorder(border);
        jPanel2.add(tempNomSousAgent[i]);
        
        tempNomSousAgent[i].setBounds(y,10, 40, 30);
           y+=40;
         
         
        }
         javax.swing.JLabel temps_att_moyen= new javax.swing.JLabel();
         temps_att_moyen.setText("Temps d'attente moyen est : "+res[0]+"");
         temps_att_moyen.setForeground(new java.awt.Color(0, 153, 153));
         jPanel2.add(temps_att_moyen);
        
         temps_att_moyen.setBounds(20, 50, 200, 20);
         javax.swing.JLabel temps_rot_moyen= new javax.swing.JLabel();
         temps_rot_moyen.setText("Temps de rotation moyen est : "+res[1]+"");
         temps_rot_moyen.setForeground(new java.awt.Color(0, 153, 153));
         jPanel2.add(temps_rot_moyen);
        
         temps_rot_moyen.setBounds(230, 50, 200, 20);
     

     
    }//GEN-LAST:event_btn_FIFOActionPerformed

    private void btn_SJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SJFActionPerformed
       // TODO add your handling code here:
            float[] res=new float [2];
        jPanel3.removeAll();
        Border border = LineBorder.createGrayLineBorder();
        res=f7. SJF( ptr, listeProcessus);
        int y = 10;
        javax.swing.JLabel[] tempNomSousAgent = new javax.swing.JLabel[ ptr];
        for(int i=0;i<ptr;i++){ 

        tempNomSousAgent[i] = new javax.swing.JLabel();
        tempNomSousAgent[i].setText(listeProcessus[i].getNomProcessus());
        tempNomSousAgent[i].setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tempNomSousAgent[i].setForeground(new java.awt.Color(0, 153, 153));
        tempNomSousAgent[i].setBorder(border);
        jPanel3.add(tempNomSousAgent[i]);
        
        tempNomSousAgent[i].setBounds(y,10, 40, 30);
         y+=40;
         
        }
        javax.swing.JLabel temps_att_moyen= new javax.swing.JLabel();
         temps_att_moyen.setText("Temps d'attente moyen est : "+res[0]+"");
         temps_att_moyen.setForeground(new java.awt.Color(0, 153, 153));
         jPanel3.add(temps_att_moyen);
        
         temps_att_moyen.setBounds(20, 50, 200, 20);
         javax.swing.JLabel temps_rot_moyen= new javax.swing.JLabel();
         temps_rot_moyen.setText("Temps de rotation moyen est : "+res[1]+"");
         temps_rot_moyen.setForeground(new java.awt.Color(0, 153, 153));
         jPanel3.add(temps_rot_moyen);
        
         temps_rot_moyen.setBounds(230, 50, 200, 20);
      
    }//GEN-LAST:event_btn_SJFActionPerformed

    private void btn_RRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RRActionPerformed
        // TODO add your handling code here:
             jPanel4.removeAll();
             if ("".equals(txt_quant.getText()) )
        {
            JOptionPane.showMessageDialog(null," Vous devez choisir un quantium  !! "); }
             else
             {
             
              int quantium=Integer.parseInt(txt_quant.getText());
              String [] sequence =new String [1000];
              sequence =f7.roundRobin(listeProcessus, ptr, quantium);
              Border border = LineBorder.createGrayLineBorder();
              int y = 10;
              javax.swing.JLabel[] tempNomSousAgent = new javax.swing.JLabel[100];
                int taille=Integer.parseInt(sequence[0]);
                for(int i=1;i<=taille;i++){ 

                tempNomSousAgent[i-1] = new javax.swing.JLabel();
                tempNomSousAgent[i-1].setText(sequence[i]);
                tempNomSousAgent[i-1].setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                tempNomSousAgent[i-1].setForeground(new java.awt.Color(0, 153, 153));
                tempNomSousAgent[i-1].setBorder(border);
                jPanel4.add(tempNomSousAgent[i-1]);
        
                tempNomSousAgent[i-1].setBounds(y,10, 40, 30);
                 y+=40;
         
        }
             
     javax.swing.JLabel temps_att_moyen= new javax.swing.JLabel();
         temps_att_moyen.setText("Temps d'attente moyen est : "+sequence[taille+1]+"");
         temps_att_moyen.setForeground(new java.awt.Color(0, 153, 153));
         jPanel4.add(temps_att_moyen);
        
         temps_att_moyen.setBounds(20, 50, 200, 20);
         javax.swing.JLabel temps_rot_moyen= new javax.swing.JLabel();
         temps_rot_moyen.setText("Temps de rotation moyen est : "+sequence[taille+2]+"");
         temps_rot_moyen.setForeground(new java.awt.Color(0, 153, 153));
         jPanel4.add(temps_rot_moyen);
        
         temps_rot_moyen.setBounds(230, 50, 200, 20);
             }

        
        
    }//GEN-LAST:event_btn_RRActionPerformed

    private void btn_afficher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_afficher1ActionPerformed
      // TODO add your handling code here:
        if ("".equals(txt_aleatoire.getText()) )
        {
            JOptionPane.showMessageDialog(null," Vous devez choisir un nombre  !! "); }
             else
             {
               int ascii = 65;
               String nom_pr;
               int duree;
               int temps_arr;
               int priorite;
              int taille=Integer.parseInt(txt_aleatoire.getText());
              for (int i=0;i<taille;i++)
              {
              
                ascii=ascii+i;
                nom_pr=Character.toString((char)ascii);
                duree  =  ( int )( Math.random () * 10 )+1;
                temps_arr =  ( int )( Math.random () * 10 );
                priorite  =  ( int )( Math.random () * 10);
                listeProcessus = f7.registerProcessus(ptr, listeProcessus ,nom_pr ,duree,priorite,temps_arr);
                ptr++;

              
              }
             
              
            /* ########## SAUVEGARDE DE PTR ########## */

            try {
                ObjectOutputStream out1 = new ObjectOutputStream(new FileOutputStream("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/pointeurListeProcessus.txt"));
                out1.writeInt(ptr);
                out1.close();
            }
            catch (Exception e){
                e.printStackTrace();
            }

            /* ########## FIN SAUVEGARDE DE PTR ########## */
            /* ########## SAUVEGARDE DE LISTEPROCESSUS ########## */

            try {
                ObjectOutputStream out2 = new ObjectOutputStream(new FileOutputStream("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/listeProcessus.txt"));
                out2.writeObject(listeProcessus);
                out2.flush();
                out2.close();
            }
            catch (Exception e){
                e.printStackTrace();
            }

            /* ########## FIN SAUVEGARDE DE LISTEPROCESSUS ########## */
             
             }
        
        
        
    }//GEN-LAST:event_btn_afficher1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulateurs().setVisible(true);
            }
        });
           if (fich.length() > 0){
                     
                    try {
                        ObjectInputStream in1 = new ObjectInputStream(new FileInputStream("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/pointeurListeProcessus.txt"));
                        ptr = in1.readInt();
                        in1.close();
                    }
                    catch (Exception e){
                        e.printStackTrace();  
                    }
                
                }
                 
                else {
                     
                    ptr = 0;
                     
                }
          /* ########## INITIALISATION DE LISTEPROCESSUS ########## */
         
        if (fich2.length() > 0){
                     
                    try {
                        ObjectInputStream in2 = new ObjectInputStream(new FileInputStream("C:/Users/Asus/Documents/NetBeansProjects/PrcsOrdonnancement/listeProcessus.txt"));
                        listeProcessus =  (Processus[]) in2.readObject();
                        in2.close();
                    }
                    catch (Exception e){
                        e.printStackTrace();  
                    }
                
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_FIFO;
    private javax.swing.JButton btn_RR;
    private javax.swing.JButton btn_SJF;
    private javax.swing.JButton btn_afficher1;
    private javax.swing.JButton btn_ajouter1;
    private javax.swing.JButton btn_generer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JTextField txt_aleatoire;
    private javax.swing.JTextField txt_duree;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_priorite;
    private javax.swing.JTextField txt_quant;
    private javax.swing.JLabel txt_quantum;
    private javax.swing.JTextField txt_temps_arr;
    // End of variables declaration//GEN-END:variables
}
